import { currentSeason, currentSeasonId, currentSeasonYear } from './season.js';

/** Default parameter values for NBA API endpoints. */
export const defaults = {
  perMode: 'PerGame' as const,
  perMode36: 'PerGame' as const,
  perModeDetailed: 'PerGame' as const,
  measureType: 'Base' as const,
  seasonType: 'Regular Season' as const,
  seasonTypeAllStar: 'Regular Season' as const,
  season: currentSeason(),
  seasonYear: currentSeasonYear(),
  seasonId: currentSeasonId(),
  leagueId: '00' as const,
  conference: '' as const,
  division: '' as const,
  gameSegment: '' as const,
  location: '' as const,
  outcome: '' as const,
  period: 0,
  lastNGames: 0,
  month: 0,
  opponentTeamId: 0,
  paceAdjust: 'N' as const,
  plusMinus: 'N' as const,
  rank: 'N' as const,
  direction: 'DESC' as const,
  playerPosition: '' as const,
  starterBench: '' as const,
  shotClockRange: '' as const,
  seasonSegment: '' as const,
  contextMeasure: 'PTS' as const,
  clutchTime: 'Last 5 Minutes' as const,
  aheadBehind: 'Ahead or Behind' as const,
  pointDiff: 5,
  gameScope: '' as const,
  playerExperience: '' as const,
  playerOrTeam: 'Player' as const,
  startPeriod: 0,
  endPeriod: 0,
  startRange: 0,
  endRange: 0,
  rangeType: 0,
  groupQuantity: 5,
  distanceRange: 'By Zone' as const,
  scope: 'S' as const,
  defenseCategory: 'Overall' as const,
  ptMeasureType: 'SpeedDistance' as const,
} as const;
