import type { FetchClient } from '../../http/fetch-client.js';
import type { RawNBAStatsResponse } from '../../response/types.js';
import { parseStatsResponse } from '../../response/parser.js';
import type { LeagueGameFinderParams, LeagueGameFinderResponse } from '../types/league-game-finder.js';

const RESULT_SET_MAP: Record<string, string> = {
  'LeagueGameFinderResults': 'leagueGameFinderResults',
};

export async function leagueGameFinder(
  client: FetchClient,
  params: LeagueGameFinderParams,
): Promise<LeagueGameFinderResponse> {
  const apiParams: Record<string, string | number | undefined> = {
    'PlayerOrTeam': params.playerOrTeam,
    'Conference': params.conference,
    'DateFrom': params.dateFrom,
    'DateTo': params.dateTo,
    'Division': params.division,
    'DraftNumber': params.draftNumber,
    'DraftRound': params.draftRound,
    'DraftTeamID': params.draftTeamID,
    'DraftYear': params.draftYear,
    'EqAST': params.eqAST,
    'EqBLK': params.eqBLK,
    'EqDD': params.eqDD,
    'EqDREB': params.eqDREB,
    'EqFG3A': params.eqFG3A,
    'EqFG3M': params.eqFG3M,
    'EqFG3_PCT': params.eqFG3_PCT,
    'EqFGA': params.eqFGA,
    'EqFGM': params.eqFGM,
    'EqFG_PCT': params.eqFG_PCT,
    'EqFTA': params.eqFTA,
    'EqFTM': params.eqFTM,
    'EqFT_PCT': params.eqFT_PCT,
    'EqMINUTES': params.eqMINUTES,
    'EqOREB': params.eqOREB,
    'EqPF': params.eqPF,
    'EqPTS': params.eqPTS,
    'EqREB': params.eqREB,
    'EqSTL': params.eqSTL,
    'EqTD': params.eqTD,
    'EqTOV': params.eqTOV,
    'GameID': params.gameID,
    'GtAST': params.gtAST,
    'GtBLK': params.gtBLK,
    'GtDD': params.gtDD,
    'GtDREB': params.gtDREB,
    'GtFG3A': params.gtFG3A,
    'GtFG3M': params.gtFG3M,
    'GtFG3_PCT': params.gtFG3_PCT,
    'GtFGA': params.gtFGA,
    'GtFGM': params.gtFGM,
    'GtFG_PCT': params.gtFG_PCT,
    'GtFTA': params.gtFTA,
    'GtFTM': params.gtFTM,
    'GtFT_PCT': params.gtFT_PCT,
    'GtMINUTES': params.gtMINUTES,
    'GtOREB': params.gtOREB,
    'GtPF': params.gtPF,
    'GtPTS': params.gtPTS,
    'GtREB': params.gtREB,
    'GtSTL': params.gtSTL,
    'GtTD': params.gtTD,
    'GtTOV': params.gtTOV,
    'LeagueID': params.leagueID,
    'Location': params.location,
    'LtAST': params.ltAST,
    'LtBLK': params.ltBLK,
    'LtDD': params.ltDD,
    'LtDREB': params.ltDREB,
    'LtFG3A': params.ltFG3A,
    'LtFG3M': params.ltFG3M,
    'LtFG3_PCT': params.ltFG3_PCT,
    'LtFGA': params.ltFGA,
    'LtFGM': params.ltFGM,
    'LtFG_PCT': params.ltFG_PCT,
    'LtFTA': params.ltFTA,
    'LtFTM': params.ltFTM,
    'LtFT_PCT': params.ltFT_PCT,
    'LtMINUTES': params.ltMINUTES,
    'LtOREB': params.ltOREB,
    'LtPF': params.ltPF,
    'LtPTS': params.ltPTS,
    'LtREB': params.ltREB,
    'LtSTL': params.ltSTL,
    'LtTD': params.ltTD,
    'LtTOV': params.ltTOV,
    'Outcome': params.outcome,
    'PORound': params.pORound,
    'PlayerID': params.playerID,
    'RookieYear': params.rookieYear,
    'Season': params.season,
    'SeasonSegment': params.seasonSegment,
    'SeasonType': params.seasonType,
    'StarterBench': params.starterBench,
    'TeamID': params.teamID,
    'VsConference': params.vsConference,
    'VsDivision': params.vsDivision,
    'VsTeamID': params.vsTeamID,
    'YearsExperience': params.yearsExperience,
  };

  const raw = await client.get<RawNBAStatsResponse>('/stats/leaguegamefinder', apiParams);
  return parseStatsResponse(raw, RESULT_SET_MAP) as unknown as LeagueGameFinderResponse;
}
