import type { FetchClient } from "../../http/fetch-client.js";
import { parseStatsResponse } from "../../response/parser.js";
import type { RawNBAStatsResponse } from "../../response/types.js";
import type {
	TeamGameStreakFinderParams,
	TeamGameStreakFinderResponse,
} from "../types/team-game-streak-finder.js";

const RESULT_SET_MAP: Record<string, string> = {
	TeamGameStreakFinderParametersResults:
		"teamGameStreakFinderParametersResults",
};

export async function teamGameStreakFinder(
	client: FetchClient,
	params: TeamGameStreakFinderParams,
): Promise<TeamGameStreakFinderResponse> {
	const apiParams: Record<string, string | number | undefined> = {
		ActiveStreaksOnly: params.activeStreaksOnly,
		ActiveTeamsOnly: params.activeTeamsOnly,
		BtrOPPAST: params.btrOPPAST,
		BtrOPPBLK: params.btrOPPBLK,
		BtrOPPDREB: params.btrOPPDREB,
		BtrOPPFG3A: params.btrOPPFG3A,
		BtrOPPFG3M: params.btrOPPFG3M,
		BtrOPPFG3PCT: params.btrOPPFG3PCT,
		BtrOPPFGA: params.btrOPPFGA,
		BtrOPPFGM: params.btrOPPFGM,
		BtrOPPFG_PCT: params.btrOPPFG_PCT,
		BtrOPPFTA: params.btrOPPFTA,
		BtrOPPFTM: params.btrOPPFTM,
		BtrOPPFT_PCT: params.btrOPPFT_PCT,
		BtrOPPOREB: params.btrOPPOREB,
		BtrOPPPF: params.btrOPPPF,
		BtrOPPPTS: params.btrOPPPTS,
		BtrOPPPTS2NDCHANCE: params.btrOPPPTS2NDCHANCE,
		BtrOPPPTSFB: params.btrOPPPTSFB,
		BtrOPPPTSOFFTOV: params.btrOPPPTSOFFTOV,
		BtrOPPPTSPAINT: params.btrOPPPTSPAINT,
		BtrOPPREB: params.btrOPPREB,
		BtrOPPSTL: params.btrOPPSTL,
		BtrOPPTOV: params.btrOPPTOV,
		Conference: params.conference,
		DateFrom: params.dateFrom,
		DateTo: params.dateTo,
		Division: params.division,
		EqAST: params.eqAST,
		EqBLK: params.eqBLK,
		EqDD: params.eqDD,
		EqDREB: params.eqDREB,
		EqFG3A: params.eqFG3A,
		EqFG3M: params.eqFG3M,
		EqFG3_PCT: params.eqFG3_PCT,
		EqFGA: params.eqFGA,
		EqFGM: params.eqFGM,
		EqFG_PCT: params.eqFG_PCT,
		EqFTA: params.eqFTA,
		EqFTM: params.eqFTM,
		EqFT_PCT: params.eqFT_PCT,
		EqMINUTES: params.eqMINUTES,
		EqOPPPTS2NDCHANCE: params.eqOPPPTS2NDCHANCE,
		EqOPPPTSFB: params.eqOPPPTSFB,
		EqOPPPTSOFFTOV: params.eqOPPPTSOFFTOV,
		EqOPPPTSPAINT: params.eqOPPPTSPAINT,
		EqOREB: params.eqOREB,
		EqPF: params.eqPF,
		EqPTS: params.eqPTS,
		EqPTS2NDCHANCE: params.eqPTS2NDCHANCE,
		EqPTSFB: params.eqPTSFB,
		EqPTSOFFTOV: params.eqPTSOFFTOV,
		EqPTSPAINT: params.eqPTSPAINT,
		EqREB: params.eqREB,
		EqSTL: params.eqSTL,
		EqTD: params.eqTD,
		EqTOV: params.eqTOV,
		GameID: params.gameID,
		GtAST: params.gtAST,
		GtBLK: params.gtBLK,
		GtDD: params.gtDD,
		GtDREB: params.gtDREB,
		GtFG3A: params.gtFG3A,
		GtFG3M: params.gtFG3M,
		GtFG3_PCT: params.gtFG3_PCT,
		GtFGA: params.gtFGA,
		GtFGM: params.gtFGM,
		GtFG_PCT: params.gtFG_PCT,
		GtFTA: params.gtFTA,
		GtFTM: params.gtFTM,
		GtFT_PCT: params.gtFT_PCT,
		GtMINUTES: params.gtMINUTES,
		GtOPPAST: params.gtOPPAST,
		GtOPPBLK: params.gtOPPBLK,
		GtOPPDREB: params.gtOPPDREB,
		GtOPPFG3A: params.gtOPPFG3A,
		GtOPPFG3M: params.gtOPPFG3M,
		GtOPPFG3PCT: params.gtOPPFG3PCT,
		GtOPPFGA: params.gtOPPFGA,
		GtOPPFGM: params.gtOPPFGM,
		GtOPPFG_PCT: params.gtOPPFG_PCT,
		GtOPPFTA: params.gtOPPFTA,
		GtOPPFTM: params.gtOPPFTM,
		GtOPPFT_PCT: params.gtOPPFT_PCT,
		GtOPPOREB: params.gtOPPOREB,
		GtOPPPF: params.gtOPPPF,
		GtOPPPTS: params.gtOPPPTS,
		GtOPPPTS2NDCHANCE: params.gtOPPPTS2NDCHANCE,
		GtOPPPTSFB: params.gtOPPPTSFB,
		GtOPPPTSOFFTOV: params.gtOPPPTSOFFTOV,
		GtOPPPTSPAINT: params.gtOPPPTSPAINT,
		GtOPPREB: params.gtOPPREB,
		GtOPPSTL: params.gtOPPSTL,
		GtOPPTOV: params.gtOPPTOV,
		GtOREB: params.gtOREB,
		GtPF: params.gtPF,
		GtPTS: params.gtPTS,
		GtPTS2NDCHANCE: params.gtPTS2NDCHANCE,
		GtPTSFB: params.gtPTSFB,
		GtPTSOFFTOV: params.gtPTSOFFTOV,
		GtPTSPAINT: params.gtPTSPAINT,
		GtREB: params.gtREB,
		GtSTL: params.gtSTL,
		GtTD: params.gtTD,
		GtTOV: params.gtTOV,
		LStreak: params.lStreak,
		LeagueID: params.leagueID,
		Location: params.location,
		LtAST: params.ltAST,
		LtBLK: params.ltBLK,
		LtDD: params.ltDD,
		LtDREB: params.ltDREB,
		LtFG3A: params.ltFG3A,
		LtFG3M: params.ltFG3M,
		LtFG3_PCT: params.ltFG3_PCT,
		LtFGA: params.ltFGA,
		LtFGM: params.ltFGM,
		LtFG_PCT: params.ltFG_PCT,
		LtFTA: params.ltFTA,
		LtFTM: params.ltFTM,
		LtFT_PCT: params.ltFT_PCT,
		LtMINUTES: params.ltMINUTES,
		LtOPPAST: params.ltOPPAST,
		LtOPPBLK: params.ltOPPBLK,
		LtOPPDREB: params.ltOPPDREB,
		LtOPPFG3A: params.ltOPPFG3A,
		LtOPPFG3M: params.ltOPPFG3M,
		LtOPPFG3PCT: params.ltOPPFG3PCT,
		LtOPPFGA: params.ltOPPFGA,
		LtOPPFGM: params.ltOPPFGM,
		LtOPPFG_PCT: params.ltOPPFG_PCT,
		LtOPPFTA: params.ltOPPFTA,
		LtOPPFTM: params.ltOPPFTM,
		LtOPPFT_PCT: params.ltOPPFT_PCT,
		LtOPPOREB: params.ltOPPOREB,
		LtOPPPF: params.ltOPPPF,
		LtOPPPTS: params.ltOPPPTS,
		LtOPPPTS2NDCHANCE: params.ltOPPPTS2NDCHANCE,
		LtOPPPTSFB: params.ltOPPPTSFB,
		LtOPPPTSOFFTOV: params.ltOPPPTSOFFTOV,
		LtOPPPTSPAINT: params.ltOPPPTSPAINT,
		LtOPPREB: params.ltOPPREB,
		LtOPPSTL: params.ltOPPSTL,
		LtOPPTOV: params.ltOPPTOV,
		LtOREB: params.ltOREB,
		LtPF: params.ltPF,
		LtPTS: params.ltPTS,
		LtPTS2NDCHANCE: params.ltPTS2NDCHANCE,
		LtPTSFB: params.ltPTSFB,
		LtPTSOFFTOV: params.ltPTSOFFTOV,
		LtPTSPAINT: params.ltPTSPAINT,
		LtREB: params.ltREB,
		LtSTL: params.ltSTL,
		LtTD: params.ltTD,
		LtTOV: params.ltTOV,
		MinGames: params.minGames,
		Outcome: params.outcome,
		PORound: params.pORound,
		Season: params.season,
		SeasonSegment: params.seasonSegment,
		SeasonType: params.seasonType,
		TeamID: params.teamID,
		VsConference: params.vsConference,
		VsDivision: params.vsDivision,
		VsTeamID: params.vsTeamID,
		WStreak: params.wStreak,
		WrsOPPAST: params.wrsOPPAST,
		WrsOPPBLK: params.wrsOPPBLK,
		WrsOPPDREB: params.wrsOPPDREB,
		WrsOPPFG3A: params.wrsOPPFG3A,
		WrsOPPFG3M: params.wrsOPPFG3M,
		WrsOPPFG3PCT: params.wrsOPPFG3PCT,
		WrsOPPFGA: params.wrsOPPFGA,
		WrsOPPFGM: params.wrsOPPFGM,
		WrsOPPFG_PCT: params.wrsOPPFG_PCT,
		WrsOPPFTA: params.wrsOPPFTA,
		WrsOPPFTM: params.wrsOPPFTM,
		WrsOPPFT_PCT: params.wrsOPPFT_PCT,
		WrsOPPOREB: params.wrsOPPOREB,
		WrsOPPPF: params.wrsOPPPF,
		WrsOPPPTS: params.wrsOPPPTS,
		WrsOPPPTS2NDCHANCE: params.wrsOPPPTS2NDCHANCE,
		WrsOPPPTSFB: params.wrsOPPPTSFB,
		WrsOPPPTSOFFTOV: params.wrsOPPPTSOFFTOV,
		WrsOPPPTSPAINT: params.wrsOPPPTSPAINT,
		WrsOPPREB: params.wrsOPPREB,
		WrsOPPSTL: params.wrsOPPSTL,
		WrsOPPTOV: params.wrsOPPTOV,
	};

	const raw = await client.get<RawNBAStatsResponse>(
		"/stats/teamgamestreakfinder",
		apiParams,
	);
	return parseStatsResponse(
		raw,
		RESULT_SET_MAP,
	) as unknown as TeamGameStreakFinderResponse;
}
